global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'Gym_CRM_SpringBoot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['Gym_CRM_SpringBoot:8080']
        labels:
          application: 'Gym_CRM_SpringBoot Application'

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
